=== Grazvy/PSEMolDyn_GroupB/input/parameters.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">



  <!-- Define elements -->
  <xs:element name="parameters">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="outputParameters" type="outputParamsType"/>
        <xs:element name="simulationParameters" type="simulationParamsType"/>
        <xs:element name="cuboids" type="cuboidType" maxOccurs="unbounded"/>
        <xs:element name="spheres" type="sphereType" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>


  <!-- Define types -->
  <xs:complexType name="outputParamsType">
    <xs:sequence>
      <xs:element name="baseName" type="xs:string"/>
      <xs:element name="writeFrequency" type="xs:int"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="simulationParamsType">
    <xs:sequence>
      <xs:element name="tEnd" type="xs:double"/>
      <xs:element name="deltaT" type="xs:double"/>
      <xs:element name="cutOfRadius" type="xs:double"/>
      <xs:element name="boundaryConditions" type="xs:string"/>
      <xs:element name="domainDimensions" type="vector3DType"/>
      <!-- Add other simulation parameters here -->
    </xs:sequence>
  </xs:complexType>

    <xs:complexType name="vector3DType">
    <xs:sequence>
      <xs:element name="x" type="xs:double"/>
      <xs:element name="y" type="xs:double"/>
      <xs:element name="z" type="xs:double"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="cuboidType">
    <xs:sequence>
      <xs:element name="position" type="vector3DType"/>
      <xs:element name="velocity" type="vector3DType"/>
      <xs:element name="dimensions" type="vector3DType"/>
      <xs:element name="mass" type="xs:double"/>
      <xs:element name="meshWidth" type="xs:double"/>
      <xs:element name="sigma" type="xs:double"/>
      <xs:element name="epsilon" type="xs:double"/>
    </xs:sequence>
  </xs:complexType>

    <xs:complexType name="sphereType">
    <xs:sequence>
      <xs:element name="center_position" type="vector3DType"/>
      <xs:element name="velocity" type="vector3DType"/>
      <xs:element name="mass" type="xs:double"/>
      <xs:element name="radius" type="xs:double"/>
      <xs:element name="meshWidth" type="xs:double"/>
      <xs:element name="sigma" type="xs:double"/>
      <xs:element name="epsilon" type="xs:double"/>
    </xs:sequence>
  </xs:complexType>

</xs:schema>

=== Grazvy/PSEMolDyn_GroupB/input/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<parameters xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="parameters.xsd">

  <!-- Output Parameters -->
  <outputParameters>
    <baseName>out</baseName>
    <writeFrequency>10</writeFrequency>
  </outputParameters>

  <!-- Simulation Parameters -->
  <simulationParameters>
    <tEnd>5</tEnd>
    <deltaT>0.0005</deltaT>
    <cutOfRadius>3.0</cutOfRadius>
    <cellSize>3.0</cellSize>
    <boundaryConditions>outflow</boundaryConditions>
    <domainDimensions> 
      <x>180</x>
      <y>90</y>
      <z>1</z>
    </domainDimensions>
  </simulationParameters>



  <!-- Cuboids -->
  <cuboids>
    <position>
      <x>20</x>
      <y>20</y>
      <z>0</z>
    </position>
    <velocity>
      <x>0</x>
      <y>0</y>
      <z>0</z>
    </velocity>
    <dimensions>
      <x>100</x>
      <y>20</y>
      <z>1</z>
    </dimensions>
    <mass>1</mass>
    <meshWidth>1.1225</meshWidth>
    <sigma>1.0</sigma>
    <epsilon>5.0</epsilon>
  </cuboids>

  <cuboids>
    <position>
      <x>70</x>
      <y>60</y>
      <z>0</z>
    </position>
    <velocity>
      <x>0</x>
      <y>-10</y>
      <z>0</z>
    </velocity>
    <dimensions>
      <x>20</x>
      <y>20</y>
      <z>1</z>
    </dimensions>
    <mass>1</mass>
    <meshWidth>1.1225</meshWidth>
    <sigma>1.0</sigma>
    <epsilon>5.0</epsilon>
  </cuboids>

  <!-- Add arbitrarily many cuboids here  -->





  <!-- Spheres -->


  <!-- Add arbitrarily many spheres here  -->

</parameters>
